### ISSUE TITLE
Occasional benchmark failure

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#1062]
At least one of the benchmarks is failing on a weekly basis during CI runs. Below is the output from one.

It's not always the same benchmark. It seems to usually be a document insert with 1,000 documents, not smaller. I've seen it happen with both schema and instance inserts.

```
>>> bench/document-instance-insert-first-1000-simple.js (>=5 samples)
AssertionError: expected 400 to equal 200
    at Object.verifyInsertSuccess (/home/runner/work/terminusdb/terminusdb/tests/lib/document.js:183:23)
    at h.afterEach (/home/runner/work/terminusdb/terminusdb/tests/bench/document-instance-insert-first.template.js:25:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async o (/home/runner/work/terminusdb/terminusdb/tests/node_modules/buffalo-bench/dist/index.min.js:1:942)
    at async h.runSample (/home/runner/work/terminusdb/terminusdb/tests/node_modules/buffalo-bench/dist/index.min.js:1:2830)
    at async h.run (/home/runner/work/terminusdb/terminusdb/tests/node_modules/buffalo-bench/dist/index.min.js:1:3109)
    at async main (/home/runner/work/terminusdb/terminusdb/tests/bench.js:66:5) {
  code: undefined,
  name: 'AfterEachError',
  statusCode: 2,
  showDiff: true,
  actual: 400,
  expected: 200,
  operator: 'strictEqual'
}
```

**Comment by spl** [comment]
I'll add something to print the response for the benchmarks.

**Comment by spl** [comment]
We haven't seen this in a few weeks. Closing as unreproducible.
