### ISSUE TITLE
updateDocument takes down client

### ISSUE THREAD

**Issue by wcoolidge** [terminusdb/terminusdb#1450]
**Describe the bug**

The symptom is an uncaught error that kills the node.js process on updateDocument despite .catch  and  enclosing try catch clauses.

The uncaught error and killed process is on both of the add, and update use-cases (last parameter create=true)

In both the add, and update use-cases,  the operation succeeds, i.e. the db insertion is successfully made despite the crashed client process.

node_modules/.pnpm/@terminusdb+terminusdb-client@10.0.17/node_modules/@terminusdb/terminusdb-client/lib/errorMessage.js:95
  const e = new Error(getAPIErrorMessage(url, options, err));
            ^
Error: API Error @type api:InsertDocumentErrorResponse api:message Tried to insert a new document with id 'terminusdb://FCWorld-v016-proto/data/SensedEntity/anchor-table-33', but an object with that id already exists api:status api:failure Code: 400 url: http://127.0.0.1:6363/api/document/admin/FCWorld-v016-proto/local/branch/main

at Object.apiErrorFormatted (/home/wac/working/workspace/.../common/temp/node_modules/.pnpm/@terminusdb+terminusdb-client@10.0.17/node_modules/@terminusdb/terminusdb-client/lib/errorMessage.js:95:13)
    at /home/wac/working/workspace/.../common/temp/node_modules/.pnpm/@terminusdb+terminusdb-client@10.0.17/node_modules/@terminusdb/terminusdb-client/lib/dispatchRequest.js:187:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: {
    '@type': 'api:InsertDocumentErrorResponse',
    'api:error': {
      '@type': 'api:DocumentIdAlreadyExists',
      'api:document': {
        '@capture': 'SensedEntity_anchor-table-33_URI',
        '@type': 'SensedEntity',
        description: 'test no 333 yy',
        name: 'anchor-table-33'
      },
      'api:document_id': 'terminusdb://FCWorld-v016-proto/data/SensedEntity/anchor-table-33'
    },
    'api:message': "Tried to insert a new document with id 'terminusdb://FCWorld-v016-proto/data/SensedEntity/anchor-table-33', but an object with that id already exists",
    'api:status': 'api:failure'
  },
  status: 400
}
The script failed with exit code 1

corresponding server output:
wac@wac-sdu-hp:~/working/workspace/tdb/terminusdb(main)$ ./terminusdb serve -i
% Started server at http://localhost:6363/
% TerminusDB server started at Thursday, Sep 08, 13:57:04 CEST (utime 1662638224.129164) args [serve,help(false),memory(_9156),interactive(true)]
% Welcome to TerminusDB's terminusdb-server, version 10.1.5!
% You can view your server in a browser at 'http://localhost:6363'

% Break level 1
[1]  ?- [INFO] 2022-09-08T13:57:18.250937+02:00 POST /api/document/admin/FCWorld-v016-proto/local/branch/main?graph_type=instance&author=admin&message=doc%20insert (400)
[INFO] 2022-09-08T13:57:18.254054+02:00 PUT /api/document/admin/FCWorld-v016-proto/local/branch/main?graph_type=instance&author=admin&message=doc%20insert&create=false (200)

I fetched terminusdb today as I saw work related to updateDocument and catch and it appears that this error may be more severe after the fetch as I was not crashing everytime earlier.

**To Reproduce**
The document array on insert is 2 docs that both use @capture to unique variable names and one of the docs refers to the other via @ref. This is equivalent to the Tom & Jerry example.

terminusdb server version:
git log --oneline -4
c8b0601d (HEAD -> main, origin/main, origin/HEAD) Diff error handler (#1444)
e927accd Adding scope type to OpenAPI spec (#1446)
acedfe4f match prefixes that further colons are part of the suffix (#1443)
b97de1e6 Fix typeof triggering on suspend (#1442)

terminusdb-client is 10.0.17 js.

**Expected behavior**

No exceptions that can't be handled are thrown  under 'add' or 'update' mode, no client crash when using large arrays of docs linked by unique variables defined by @capture and referenced by @ref

**Screenshots**

Ubuntu 20.04
manual terminusdb server fetched and made today
terminusdb-client is 10.0.17 js.
swi-prolog 8.4.3-1-g10c53c6e3-focalppa2
terminus_store_prolog 0-19.8
typescript
node.js v16.6.0

**Comment by wcoolidge** [comment]
I changed the wording on expected behavior which was not clear. Currently I am getting an exception that I cannot handle that takes down the client. I am fine with errors that I can handle assuming that there is no issue (performance or otherwise) with a large array of objects.  I am trying to do a single query of a large cluster of documents and I assume that an array of documents via updateDocument is the preferred way of doing it (rather than via WOQL).

**Comment by wcoolidge** [comment]
My bad! Of course it was my mistake and I am sorry to have wasted every one's time on this!

Once I had a clear head I realized that the exception that was re thrown from axios was not not getting caught on the WOQLClient and I found why it why it was not getting through.... 

 I am closing this!
