### ISSUE TITLE
Upgrading 10-to-11 fails with error

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1707]
**Describe the bug**
To try to run the upgrade, I use docker like so:

```
cp -r terminusdb/db_10/db/ convert/db10
docker run --rm -it -e RUST_BACKTRACE=1 -v "`pwd`"/db10:/db10 -v "`pwd`"/db11:/db11 -v "`pwd`"/work10-to-11:/work10-to-11 --entrypoint=/app/terminusdb-upgrade/bin/terminusdb-10-to-11 terminusdb/terminusdb-upgrade:latest convert-store /db10 /db11 -w /work10-to-11
```

**To Reproduce**
1. Run the docker command to upgrade (used the same as in the script in the upgrade docker)

**Expected behavior**

**Screenshots**

Stacktrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "string not len 40" }', src/reachable.rs:157:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: terminusdb_10_to_11::convert_store::convert_store::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: tokio::runtime::park::CachedParkThread::block_on
   9: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  10: tokio::runtime::runtime::Runtime::block_on
  11: terminusdb_10_to_11::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Info (please complete the following information):**
 - OS: Docker on Debian 9.13

**Additional context**
This is an old instance I have been running since more than a year I think.

**Comment by GavinMendelGleason** [comment]
It would be useful to get the error file. We'll try to put together a command that can retrieve it tomorrow.

**Comment by hoijnet** [comment]
The work folder is completely empty after receiving the error, not even the error log. It only runs for a few seconds before failing.

**Comment by matko** [comment]
Is this still an issue for you?

**Comment by hoijnet** [comment]
Yes, I tried a few days back and it was not working. Have you made updates on this specific issue? @GavinMendelGleason  has received a copy of the offending repo and had some ideas.
