### ISSUE TITLE
error: failed to run custom build command for `terminusdb-grpc-labelstore-proto v0.1.0

### ISSUE THREAD

**Issue by heiheshang** [terminusdb/terminusdb#1780]
**Describe the bug**
`error: failed to run custom build command for `terminusdb-grpc-labelstore-proto v0.1.0 (https://github.com/terminusdb-labs/terminusdb-grpc-labelstore?rev=0fad3a896f2fa221af76af4c4325333109345386#0fad3a89)`

Caused by:
  process didn't exit successfully: `/home/oper/Programs/terminusdb/src/rust/target/release/build/terminusdb-grpc-labelstore-proto-c22f40e1ef51eb09/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./labels.proto
  cargo:rerun-if-changed=.

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /home/oper/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.8/src/lib.rs:1434:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `swipl-fli v0.3.4`

Caused by:
  process didn't exit successfully: `/home/oper/Programs/terminusdb/src/rust/target/release/build/swipl-fli-27b99a95bc6ca9cd/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=swipl
  cargo:rustc-link-search=/usr/local/lib/swipl/lib/x86_64-linux
  cargo:rerun-if-changed=c/wrapper.h
  cargo:rerun-if-env-changed=SWIPL

  --- stderr
  /usr/local/lib/swipl/include/SWI-Stream.h:58:10: fatal error: 'stdarg.h' file not found
  /usr/local/lib/swipl/include/SWI-Stream.h:58:10: fatal error: 'stdarg.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/oper/.cargo/registry/src/github.com-1ecc6299db9ec823/swipl-fli-0.3.4/build.rs:18:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make[2]: *** [distribution/Makefile.rust:51: src/rust/target/release/libterminusdb_dylib.so] Ошибка 101
make[2]: выход из каталога «/home/oper/Programs/terminusdb»
make[1]: *** [distribution/Makefile.prolog:78: src/rust/librust.so] Ошибка 2
make[1]: выход из каталога «/home/oper/Programs/terminusdb»
make: *** [Makefile:12: default] Ошибка 2
oper@linux-9y35:~/Programs/terminusdb> cargo --version
cargo 1.68.2 (6feb7c9cf 2023-03-26)`

**To Reproduce**
1. Go to 'make'
`make
make[1]: вход в каталог «/home/oper/Programs/terminusdb»
make[2]: вход в каталог «/home/oper/Programs/terminusdb»
cd src/rust && cargo build --profile release
   Compiling terminusdb-grpc-labelstore-proto v0.1.0 (https://github.com/terminusdb-labs/terminusdb-grpc-labelstore?rev=0fad3a896f2fa221af76af4c4325333109345386#0fad3a89)
   Compiling swipl-fli v0.3.4
   Compiling unicode-segmentation v1.10.1
   Compiling ascii v0.9.3
   Compiling unicode-bidi v0.3.13
   Compiling ryu v1.0.13
   Compiling terminus-store v0.20.1 (https://github.com/terminusdb/terminusdb-store?branch=main#a6660099)
   Compiling smartstring v1.0.1
error: failed to run custom build command for `terminusdb-grpc-labelstore-proto v0.1.0 (https://github.com/terminusdb-labs/terminusdb-grpc-labelstore?rev=0fad3a896f2fa221af76af4c4325333109345386#0fad3a89)`

Caused by:
  process didn't exit successfully: `/home/oper/Programs/terminusdb/src/rust/target/release/build/terminusdb-grpc-labelstore-proto-c22f40e1ef51eb09/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./labels.proto
  cargo:rerun-if-changed=.

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /home/oper/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.8/src/lib.rs:1434:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `swipl-fli v0.3.4`

Caused by:
  process didn't exit successfully: `/home/oper/Programs/terminusdb/src/rust/target/release/build/swipl-fli-27b99a95bc6ca9cd/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=swipl
  cargo:rustc-link-search=/usr/local/lib/swipl/lib/x86_64-linux
  cargo:rerun-if-changed=c/wrapper.h
  cargo:rerun-if-env-changed=SWIPL

  --- stderr
  /usr/local/lib/swipl/include/SWI-Stream.h:58:10: fatal error: 'stdarg.h' file not found
  /usr/local/lib/swipl/include/SWI-Stream.h:58:10: fatal error: 'stdarg.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/oper/.cargo/registry/src/github.com-1ecc6299db9ec823/swipl-fli-0.3.4/build.rs:18:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Building [====================>    ] 295/339: terminus-store `
**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - `cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20230326"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230326"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20230326"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"`

`swipl --version
SWI-Prolog version 9.1.7 for x86_64-linux`

**Comment by heiheshang** [comment]
How can I fix this quickly?

**Comment by matko** [comment]
install protoc, which in debian comes with the protobuf-compiler package.

**Comment by heiheshang** [comment]
now i got this error
`error: failed to run custom build command for `swipl-fli v0.3.4`

Caused by:
  process didn't exit successfully: `/home/oper/Programs/terminusdb/src/rust/target/release/build/swipl-fli-28e74605e412725e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=swipl
  cargo:rustc-link-search=/usr/local/lib/swipl/lib/x86_64-linux
  cargo:rerun-if-changed=c/wrapper.h
  cargo:rerun-if-env-changed=SWIPL

  --- stderr
  /usr/local/lib/swipl/include/SWI-Stream.h:58:10: fatal error: 'stdarg.h' file not found
  /usr/local/lib/swipl/include/SWI-Stream.h:58:10: fatal error: 'stdarg.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/oper/.cargo/registry/src/github.com-1ecc6299db9ec823/swipl-fli-0.3.4/build.rs:18:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make[2]: *** [distribution/Makefile.rust:51: src/rust/target/release/libterminusdb_dylib.so] Ошибка 101
make[2]: выход из каталога «/home/oper/Programs/terminusdb»
make[1]: *** [distribution/Makefile.prolog:78: src/rust/librust.so] Ошибка 2
make[1]: выход из каталога «/home/oper/Programs/terminusdb»
make: *** [Makefile:12: default] Ошибка 2`

**Comment by matko** [comment]
Could be that you haven't installed clang. Please try that.

**Comment by heiheshang** [comment]
next problem
`53:     0x5558c0553925 - _start
                                 at /home/abuild/rpmbuild/BUILD/glibc-2.37/csu/../sysdeps/x86_64/start.S:115
    54:                0x0 - <unknown>
make[2]: *** [distribution/Makefile.rust:51: src/rust/target/release/libterminusdb_dylib.so] Ошибка 101
make[2]: выход из каталога «/home/oper/Programs/terminusdb»
make[1]: *** [distribution/Makefile.prolog:78: src/rust/librust.so] Ошибка 2
`

**Comment by hoijnet** [comment]
Build dependencies added to the Dockerfile to make it easy to understand how to build. See issue #2153 for details.

Closing this. Please reopen if the Dockerfile info does not help.
