### ISSUE TITLE
race condition with new layers in a multi-server setup

### ISSUE THREAD

**Issue by geoffwhittington** [terminusdb/terminusdb#1868]
**Describe the bug**
Trigger a server error: 

```
Traceback (most recent call last):
  File "update.py", line 77, in <module>
    go()
  File "update.py", line 73, in go
    uploaded_tasks = upload_unique_tasks(unique_tasks)
  File "update.py", line 46, in upload_unique_tasks
    response = client.insert_document(
  File "/home/xxxx/comps/.pyenv/lib/python3.8/site-packages/terminusdb_client/client/Client.py", line 1248, in insert_document
    result = json.loads(_finish_response(result))
  File "/home/xxxx/comps/.pyenv/lib/python3.8/site-packages/terminusdb_client/woql_utils.py", line 52, in _finish_response
    raise DatabaseError(request_response)
terminusdb_client.errors.DatabaseError: Error: rust_error(panic("called `Option::unwrap()` on a `None` value"))
  [41] terminus_store:store_id_layer(<store>,"6ad6d51773bd2dd7331c7633ca24a98c1a35b0a6",_17920)
  [40] descriptor:open_read_write_obj(branch_graph{branch_name:"main",database_name:"Components2",organization_name:"XXXXX",repository_name:"local",type:schema},_17958,[... = ...,...|...],[... = _18016,...|...]) at /app/terminusdb/src/core/transaction/descriptor.pl:330
  [39] utils:mapm_([branch_graph{branch_name:"main",database_name:"Components2",organization_name:"XXXX",repository_name:"local",type:schema}],[_18100],[... = ...,...|...],_18064,descriptor:open_read_write_obj) at /app/terminusdb/src/core/util/utils.pl:544
  [36] descriptor:open_descriptor_(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},commit_info{},_18166,[],[... = _18210|_18204]) at /app/terminusdb/src/core/transaction/descriptor.pl:597
  [35] descriptor:open_descriptor(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},commit_info{},_18250,[],[... = _18294|_18288]) at /app/terminusdb/src/core/transaction/descriptor.pl:698
  [34] descriptor:open_descriptor(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},commit_info{},_18334) at /app/terminusdb/src/core/transaction/descriptor.pl:705
  [32] ask:create_context_(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},_18400) at /app/terminusdb/src/core/query/ask.pl:236
  [30] ask:create_context(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},commit_info{author:admin,message:'Commit via python client 10.2.3'},_18464) at /app/terminusdb/src/core/query/ask.pl:249
  [29] utils:do_or_die(api_document:create_context(...,...,_18552),error(unresolvable_collection(...),_18558)) at /app/terminusdb/src/core/util/utils.pl:149
  [28] api_document:before_write(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},admin,'Commit via python client 10.2.3',no_data_version,_18606,_18608) at /app/terminusdb/src/core/api/api_document.pl:44
  [27] api_document:api_insert_documents('<garbage_collected>','terminusdb://system/data/User/google-oauth2%7C115503261831498166673','XXXXXX/Components2/local/branch/main',<stream>(0x55b6f07e8200),no_data_version,_18678,_18680,'<garbage_collected>') at /app/terminusdb/src/core/api/api_document.pl:314
  [26] '<meta-call>'('<garbage_collected>') <foreign>
  [25] catch(routes:(...,...),error(rust_error(...),context(_18776,_18778)),routes:do_or_die(...,...)) at /usr/lib/swipl/boot/init.pl:565
  [24] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:645

```

**To Reproduce**
1. Run a custom import 

**Expected behavior**
I don't expect an error

**Screenshots**
N/A

**Info (please complete the following information):**
 - Running against SaaS instance terminuscms

**Additional context**
N/A

**Comment by geoffwhittington** [comment]
This seems to be a timing issue. If I put in a `time.sleep(1)` between inserts I don't see this error.

**Comment by matko** [comment]
The server definitely shouldn't be returning rust panics under any circumstance.

Can you tell me roughly what your import does? What steps does it go through (db creation, schema creation, etc)? And where does it start failing?

**Comment by geoffwhittington** [comment]
I've triggered the error in the following function. The `time.sleep(1)` allows it to work without an issue.

```
def upload_unique_tasks(tasks):
    new_tasks = {}
    # delete all tasks in terminus
    docs = client.get_documents_by_type(doc_type="DocumentType")
    client.delete_document(docs)
    # insert all tasks and keep a record of their document id
    for task_id, task in tasks.items():
        print(task)
        time.sleep(1)
        doc = {"@type": "DocumentType", "name": task["Title"], "item_id": task["ID"]}

        try:
            response = client.insert_document(doc)
        except Exception as e:
            print(task)
            print(doc)
            raise e
        new_tasks[task["ID"]] = response[0]
    return new_tasks
```

**Comment by matko** [comment]
The fact that things work when you do sleep indicates that maybe the issue here is when you hit different servers in subsequent requests, and somehow the layer file did not get synced properly.
This is pretty weird, since the layer storage code does try to ensure that everything has been synced to the filesystem before returning.
I'll investigate if there's some weird issue going on with NFS that might mean that 'synced to filesystem' means something different for NFS.

**Comment by dfrnt-SigmundFuchs** [comment]
This issue has been closed due to inactivity. Please don’t hesitate to reopen it if you have any further questions or would like to continue the discussion.
