### ISSUE TITLE
what is missing to build the release?

### ISSUE THREAD

**Issue by heiheshang** [terminusdb/terminusdb#1873]
make

`cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20230608"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230608"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20230608"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"`

`thread 'main' panicked at '"__mbstate_t_union_(unnamed_at_/usr/include/bits/types/__mbstate_t_h_16_3)" is not a valid Ident', /home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/fallback.rs:811:9
  stack backtrace:
     0:     0x5654dbb431ba - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5654dbb431ba - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5654dbb431ba - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x5654dbb431ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x5654dbb683cf - core::fmt::write::h9ffde816c577717b
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
     5:     0x5654dbb400f5 - std::io::Write::write_fmt::h88186074961638e4
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
     6:     0x5654dbb42f85 - std::sys_common::backtrace::_print::h184198273ed08d59
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x5654dbb42f85 - std::sys_common::backtrace::print::h1b4d8e7add699453
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x5654dbb4462e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
     9:     0x5654dbb443d5 - std::panicking::default_hook::h48c64f31d8b3fd03
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
    10:     0x5654dbb44b8e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
    11:     0x5654dbb44a89 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
    12:     0x5654dbb43626 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
    13:     0x5654dbb447e2 - rust_begin_unwind
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
    14:     0x5654db6b6473 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
    15:     0x5654db97f4c4 - proc_macro2::fallback::validate_ident::hd381776a7244bddf
    16:     0x5654db97f2d9 - proc_macro2::fallback::Ident::_new::hbc5c34839f399547
    17:     0x5654db97f32f - proc_macro2::fallback::Ident::new::hee1dd3b84c2b9f83
    18:     0x5654db96fe36 - proc_macro2::imp::Ident::new::hb602f08b0a8afc68
    19:     0x5654db97c198 - proc_macro2::Ident::new::hb9404c9905c0cf48
    20:     0x5654db7cb4cf - bindgen::ir::context::BindgenContext::rust_ident_raw::h891919ef8dfae32f
    21:     0x5654db7cb425 - bindgen::ir::context::BindgenContext::rust_ident::hde8922874354cdb3
    22:     0x5654db70d313 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h847336c32c1d0351
    23:     0x5654db7545c1 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::h95c60d0ae63d601b
    24:     0x5654db72b4a9 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h8cdf70eef8b72138
    25:     0x5654db710df5 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h847336c32c1d0351
    26:     0x5654db7545c1 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::h95c60d0ae63d601b
    27:     0x5654db72b4a9 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h8cdf70eef8b72138
    28:     0x5654db79685a - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::ha30f81eafb3b12e3
    29:     0x5654db72b742 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::heb8a45e22b5d5ed1
    30:     0x5654db72b48e - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h8cdf70eef8b72138
    31:     0x5654db7a04b4 - bindgen::codegen::codegen::{{closure}}::ha9c1cd7f9844bfa4
    32:     0x5654db7cdcb2 - bindgen::ir::context::BindgenContext::gen::h73b18614ed48aa5e
    33:     0x5654db79f5bd - bindgen::codegen::codegen::h23af96b6541b4051
    34:     0x5654db77fd50 - bindgen::Bindings::generate::ha720083a93f20f83
    35:     0x5654db77cda9 - bindgen::Builder::generate::h501ead8901e232d2
    36:     0x5654db6b870b - build_script_build::main::hf702831fffd66bae
    37:     0x5654db6b8b83 - core::ops::function::FnOnce::call_once::h6129ed1e09147cc6
    38:     0x5654db6b7476 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8f486e210f63afd6
    39:     0x5654db6b7389 - std::rt::lang_start::{{closure}}::hb09c4b6575b0dcf5
    40:     0x5654dbb3c8ee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
    41:     0x5654dbb3c8ee - std::panicking::try::do_call::h4044173225fe83dd
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
    42:     0x5654dbb3c8ee - std::panicking::try::hd8a722c09d156a53
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
    43:     0x5654dbb3c8ee - std::panic::catch_unwind::hd2ca07971cf0119b
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
    44:     0x5654dbb3c8ee - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
    45:     0x5654dbb3c8ee - std::panicking::try::do_call::hf47aa1aa005e5f1a
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
    46:     0x5654dbb3c8ee - std::panicking::try::h73d246b2423eaf4e
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
    47:     0x5654dbb3c8ee - std::panic::catch_unwind::hbaaeae8f1b2f9915
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
    48:     0x5654dbb3c8ee - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
    49:     0x5654db6b7367 - std::rt::lang_start::h58ae074e991133e3
    50:     0x5654db6b88b5 - main
    51:     0x7f718683dbb0 - __libc_start_call_main
    52:     0x7f718683dc79 - __libc_start_main_alias_1
    53:     0x5654db6b6b15 - _start
                                 at /home/abuild/rpmbuild/BUILD/glibc-2.37/csu/../sysdeps/x86_64/start.S:115
    54:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
make[2]: *** [distribution/Makefile.rust:51: src/rust/target/release/libterminusdb_dylib.so] Error 101
make[2]: Leaving directory '/home/oper/Programs/terminusdb'
make[1]: *** [distribution/Makefile.prolog:78: src/rust/librust.so] Error 2
make[1]: Leaving directory '/home/oper/Programs/terminusdb'
make: *** [Makefile:12: default] Error 2`

**Comment by GavinMendelGleason** [comment]
@rrooij any ideas?

**Comment by matko** [comment]
It's hard to say what exactly is going wrong here, as none of us run opensuse. The error seems to be occurring in bindgen, a rust utility that generates rust bindings for c libraries, and it is happening against something that seems be part of libc.

What you could try to do is run cargo update inside src/rust/ to pull in latest dependencies and recompile.

**Comment by heiheshang** [comment]
I tried, the result is the same

**Comment by dfrnt-SigmundFuchs** [comment]
This issue has been closed due to inactivity. Please don’t hesitate to reopen it if you have any further questions or would like to continue the discussion.
