### ISSUE TITLE
Invalid names in GraphQL backlinks caused by unescaped colons

### ISSUE THREAD

**Issue by timathom** [terminusdb/terminusdb#1979]
**Describe the bug**
I have [a schema](https://github.com/timathom/linked-art-terminusdb/blob/main/schema/CombinedLinkedArtSchemaExpanded.json) that contains class definitions with namespace prefixes. When I load this schema into a new data product, the GraphQL interface breaks because invalid names are generated for backlink properties:
```
{
  "errors": [
    {
      "message": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"_la_establishes_of_la:RightAcquisition\" does not.",
      "stack": "GraphQLError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"_la_establishes_of_la:RightAcquisition\" does not.\n    at l (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:16209175)\n    at w (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:16199108)\n    at y (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:16199331)\n    at https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:16198328\n    at p (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:16198498)\n    at https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:18771997\n    at Object.Xo [as useMemo] (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6400872)\n    at e.useMemo (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:15788826)\n    at SchemaContextProvider (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:18771973)\n    at xo (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6396491)\n    at Cl (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6408112)\n    at xc (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6454190)\n    at Ms (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6442475)\n    at ws (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6442403)\n    at ms (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6442266)\n    at is (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:6437402)\n    at z (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:15843404)\n    at MessagePort.S (https://dashboard.terminusdb.com/assets/8ebfa1601a1d8174ffca.js:2:15843936)"
    }
  ]
}
```

**To Reproduce**
1. Load the schema into TerminusCMS
2. View the GraphiQL query interface

**Expected behavior**
Colons in classes with namespace prefixes should be replaced with underscores to generate valid GraphQL names in backlink properties.

**Screenshots**
![Screenshot 2023-10-09 at 3 51 39 PM](https://github.com/terminusdb/terminusdb/assets/5334524/3d81d402-868d-4d85-b453-1a947f43755a)

**Info (please complete the following information):**
 - Latest TerminusCMS

**Comment by hoijnet** [comment]
Reference to similar issue: #1929

**Comment by hoijnet** [comment]
Might also be related: #1857

**Comment by GavinMendelGleason** [comment]
This should be fixed in #1980
