### ISSUE TITLE
docker doesn't start: `Authentication Incorrect for reason: basic_auth(admin)`

### ISSUE THREAD

**Issue by alexander-mart** [terminusdb/terminusdb#2051]
**Describe the bug**
I can't change defalut `TERMINUSDB_ADMIN_PASS=root` on setup with Docker.
```sh
docker compose up
```

Output:
```sh
terminusdb-server                | [ERROR] 2023-12-01T22:21:26.896009+00:00 Authentication Incorrect for reason: basic_auth(admin)
terminusdb-server                | 
terminusdb-server                | [INFO] 2023-12-01T22:21:26.900388+00:00 POST /api/organizations/terminusCR (401)
terminusdb-change-request-api-1  | An unexpected error occured during startup
terminusdb-change-request-api-1  | Error: API Error @type api:ErrorResponse api:message Incorrect authentication information api:status api:failure Code: 401 url: http://terminusdb-server:6363/api/organizations/terminusCR
terminusdb-change-request-api-1  |     at Object.apiErrorFormatted (/app/node_modules/@terminusdb/terminusdb-client/lib/errorMessage.js:95:13)
terminusdb-change-request-api-1  |     at /app/node_modules/@terminusdb/terminusdb-client/lib/dispatchRequest.js:227:30
terminusdb-change-request-api-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
terminusdb-change-request-api-1  |   data: {
terminusdb-change-request-api-1  |     '@type': 'api:ErrorResponse',
terminusdb-change-request-api-1  |     'api:error': { '@type': 'api:IncorrectAuthenticationError' },
terminusdb-change-request-api-1  |     'api:message': 'Incorrect authentication information',
terminusdb-change-request-api-1  |     'api:status': 'api:failure'
terminusdb-change-request-api-1  |   },
terminusdb-change-request-api-1  |   status: 401
terminusdb-change-request-api-1  | }
terminusdb-change-request-api-1 exited with code 1

```

**To Reproduce**
1. `git clone https://github.com/terminusdb/terminusdb`
2. `cd terminusdb`
3. `touch .env`
4. edit `docker-compose.yml` and set `services` → `change-request-api` → `environment` → `TERMINUSDB_ADMIN_PASS` and `services` → `terminusdb-server` → `environment` → `TERMINUSDB_ADMIN_PASS` to `my-strong-password-123`
5. `docker compose up`

**Expected behavior**
terminusdb docker containers start without errors

**Screenshots**
—

**Info (please complete the following information):**
terminusdb version: [`v11.1.10`](https://github.com/terminusdb/terminusdb/releases/tag/v11.1.10)

**Additional context**
If the `docker-compose.yml` file is not edited (with `TERMINUSDB_ADMIN_PASS` disabled), Docker containers start correctly (but with unsecure `root` password!)

**Comment by GavinMendelGleason** [comment]
The problem here is that the password needs to be changed using the User API before you can change it in the docker settings. This can be achieved using TerminusDB's cli (tdb-cli) with the following invocation: 

```shell
tdb-cli user set-password
```

You can see how to set up tdb-cli here: https://github.com/terminusdb-labs/tdb-cli

**Comment by paulwalk** [comment]
I am experiencing this bug too, exactly as @alexander-mart describes it above

**Comment by DrAlliteration** [comment]
I am experiencing this bug too. Is there any fix for it? (@GavinMendelGleason solution didn't work for me)
