### ISSUE TITLE
Nonsense data value gives stacktrace rather than JSON error

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#449]
When I submit a null atom instead of a decimal, I get a stack trace:

```prolog
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
  File "/home/gavin/dev/terminusdb-client-python/terminusdb_client/woqlclient/woqlClient.py", line 817, in insert_document
    return json.loads(_finish_reponse(result))
  File "/home/gavin/dev/terminusdb-client-python/terminusdb_client/woql_utils.py", line 146, in _finish_reponse
    raise DatabaseError(request_response)
terminusdb_client.errors.DatabaseError: Error: casting_error("null",'http://www.w3.org/2001/XMLSchema#decimal')
  [46] throw(error(casting_error("null",'http://www.w3.org/2001/XMLSchema#decimal'),_116566))
  [44] catch('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:533
  [42] api_document:api_insert_document_(instance,transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:"main",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},<stream>(0x556b3c37d700),_116648) at /app/terminusdb/src/core/api/api_document.pl:180
  [41] '$bags':findall_loop(_116764,'<garbage_collected>',_116768,[]) at /usr/lib/swipl/boot/bags.pl:99
  [40] setup_call_catcher_cleanup('$bags':'$new_findall_bag','$bags':findall_loop(_116822,...,_116826,[]),_116804,'$bags':'$destroy_findall_bag') at /usr/lib/swipl/boot/init.pl:614
  [36] '<meta-call>'('<garbage_collected>') <foreign>
  [35] database:with_transaction_(query_context{all_witnesses:false,authorization:'terminusdb://system/data/admin',bindings:[],commit_info:commit_info{author:admin,message:'Inserting stock exchange ticker chunk 0'},default_collection:branch_descriptor{branch_name:"main",repository_descriptor: ...},files:[],filter:type_filter{types: ...},prefixes:_116972{'@base':"terminusdb:///stock_exchange/",'@schema':"terminusdb:///stock_exchange/schema#",'@type':'Context',api:'http://terminusdb.com/schema/api#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},selected:[],system:system_descriptor{},transaction_objects:[...],update_guard:_116958,write_graph:branch_graph{branch_name:"main",database_name:"sed",organization_name:"ubf40420team",repository_name:"local",type:instance}},api_document:(...;...),_116908) at /app/terminusdb/src/core/transaction/database.pl:220
  [34] setup_call_catcher_cleanup(database:true,database:with_transaction_(...,...,_117150),_117128,database:true) at /usr/lib/swipl/boot/init.pl:614
  [32] database:with_transaction('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /app/terminusdb/src/core/transaction/database.pl:209
  [30] '<meta-call>'('<garbage_collected>') <foreign>
  [29] catch(routes:(...,...),error(casting_error("null",'http://www.w3.org/2001/XMLSchema#decimal'),context(_117292,_117294)),routes:do_or_die(...,...)) at /usr/lib/swipl/boot/init.pl:532
  [28] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:582
```

This happens in current 'main' branch.

**Comment by matko** [comment]
This has been solved in merge request #451
